version: "3.8"

services:
  nodejs:
    build: ./.docker-config/.nodejs
    volumes:
      - ./discord:/usr/src/app
    command: bash -c "npx ts-node ./src/app.ts"
    expose:
      - "6162" #既存のサービスと被らないようにした
    tty: true
    restart: always
    depends_on:
      - python

  python:
    build: ./.docker-config/.python
    volumes:
      - ./python:/usr/src/app
    command: bash -c "uvicorn main:app --host 0.0.0.0:9232 --reload"
    ports:
      - "9232:9232" #既存のサービスと被らないようにした
    tty: true
    restart: always